### PR TITLE
Fix all the bugs

### LINKED ISSUE #31: If a user is already a collaborator to an app (even if it's just view permissions) this script fails
Heroku have changed their API (fair enough because it wasn't documented).  You used to be able to ‘upsert’.  Now we're going to need either send a `PATCH` to `https://api.heroku.com/organizations/apps/"+app+"/collaborators/email.address@ft.com` if the user is already a collaborator to the app or follow the current logic if they are not.

https://github.com/Financial-Times/heroku-permissions/blob/master/heroku/heroku.go#L115-L118

### PR DESCRIPTION
**Pull request by matthew-andrews**
Stops this from being completely broken, also fixes #31!

### CODE REVIEW

File: heroku/heroku.go [hunk 1]
```diff
@@ -9,7 +9,8 @@ import (
 )
 
 const (
-	PartialPermissions = iota
+	NoPermissions = iota
```
Comment (matthew-andrews) [inline heroku/heroku.go]: this caused some utterly bonkers bugs
